-- -----------------------------------------------------
-- Table `PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRODUCT`
(
  `PRODUCT_ID`				VARCHAR(255) generated by default as identity,
  `PRODUCT_NAME`			VARCHAR(255) NOT NULL,
  `ADDRESS`					VARCHAR(255) NOT NULL,
  `DETAIL_ADDRESS`			VARCHAR(255) NOT NULL,
  `PRICE`					VARCHAR(255) NOT NULL,
  `CREATED_AT`				TIMESTAMP    NULL,
  `UPDATED_AT`				TIMESTAMP    NULL,
  PRIMARY KEY (`PRODUCT_ID`)
);
